name: biblioteca_dart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: JulioCezar_1991 <JulioCezar_1991@hotmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  rxdart: ^0.22.3
  http: ^0.12.0+2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
